[package]
name = "mqtt-proto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std"]
std = []

[dependencies]
bytes = "1.3.0"
futures-lite = "1.12.0"
thiserror = "1.0.38"
simdutf8 = "0.1.4"

# Only for fuzz testing
arbitrary = { version = "1.2.3", optional = true, features = ["derive"] }

[dev-dependencies]
proptest = "1.0.0"
